from resolucion_ejercicios_lineales import *

ejercicio_1()
# ejercicio_2()
# ejercicio_3()
# ejercicio_4()
# ejercicio_5()
# ejercicio_6()
# ejercicio_7()
# ejercicio_8()
# ejercicio_9()
# ejercicio_10()
# ejercicio_11()
# ejercicio_12()
# ejercicio_13()
# ejercicio_14()